/*
 *  ======== clb.c ========
 *  DO NOT EDIT - This file is generated by the SysConfig tool.
 */

#include "driverlib.h"
#include "device.h"
#include "clb_config.h"
#include "clb.h"


const uint32_t CLBTILE5_HLC_initFIFOData[4] = {CLBTILE5_HLC_FIFO0_INIT, CLBTILE5_HLC_FIFO1_INIT, CLBTILE5_HLC_FIFO2_INIT, CLBTILE5_HLC_FIFO3_INIT};

uint16_t CLBTILE5HLCInstr[CLB_NUM_HLC_INSTR + 1] =
{
    CLBTILE5_HLCINSTR_0,
    CLBTILE5_HLCINSTR_1,
    CLBTILE5_HLCINSTR_2,
    CLBTILE5_HLCINSTR_3,
    CLBTILE5_HLCINSTR_4,
    CLBTILE5_HLCINSTR_5,
    CLBTILE5_HLCINSTR_6,
    CLBTILE5_HLCINSTR_7,
    CLBTILE5_HLCINSTR_8,
    CLBTILE5_HLCINSTR_9,
    CLBTILE5_HLCINSTR_10,
    CLBTILE5_HLCINSTR_11,
    CLBTILE5_HLCINSTR_12,
    CLBTILE5_HLCINSTR_13,
    CLBTILE5_HLCINSTR_14,
    CLBTILE5_HLCINSTR_15,
    CLBTILE5_HLCINSTR_16,
    CLBTILE5_HLCINSTR_17,
    CLBTILE5_HLCINSTR_18,
    CLBTILE5_HLCINSTR_19,
    CLBTILE5_HLCINSTR_20,
    CLBTILE5_HLCINSTR_21,
    CLBTILE5_HLCINSTR_22,
    CLBTILE5_HLCINSTR_23,
    CLBTILE5_HLCINSTR_24,
    CLBTILE5_HLCINSTR_25,
    CLBTILE5_HLCINSTR_26,
    CLBTILE5_HLCINSTR_27,
    CLBTILE5_HLCINSTR_28,
    CLBTILE5_HLCINSTR_29,
    CLBTILE5_HLCINSTR_30,
    CLBTILE5_HLCINSTR_31
};


const uint32_t CLBTILE6_HLC_initFIFOData[4] = {CLBTILE6_HLC_FIFO0_INIT, CLBTILE6_HLC_FIFO1_INIT, CLBTILE6_HLC_FIFO2_INIT, CLBTILE6_HLC_FIFO3_INIT};

uint16_t CLBTILE6HLCInstr[CLB_NUM_HLC_INSTR + 1] =
{
    CLBTILE6_HLCINSTR_0,
    CLBTILE6_HLCINSTR_1,
    CLBTILE6_HLCINSTR_2,
    CLBTILE6_HLCINSTR_3,
    CLBTILE6_HLCINSTR_4,
    CLBTILE6_HLCINSTR_5,
    CLBTILE6_HLCINSTR_6,
    CLBTILE6_HLCINSTR_7,
    CLBTILE6_HLCINSTR_8,
    CLBTILE6_HLCINSTR_9,
    CLBTILE6_HLCINSTR_10,
    CLBTILE6_HLCINSTR_11,
    CLBTILE6_HLCINSTR_12,
    CLBTILE6_HLCINSTR_13,
    CLBTILE6_HLCINSTR_14,
    CLBTILE6_HLCINSTR_15,
    CLBTILE6_HLCINSTR_16,
    CLBTILE6_HLCINSTR_17,
    CLBTILE6_HLCINSTR_18,
    CLBTILE6_HLCINSTR_19,
    CLBTILE6_HLCINSTR_20,
    CLBTILE6_HLCINSTR_21,
    CLBTILE6_HLCINSTR_22,
    CLBTILE6_HLCINSTR_23,
    CLBTILE6_HLCINSTR_24,
    CLBTILE6_HLCINSTR_25,
    CLBTILE6_HLCINSTR_26,
    CLBTILE6_HLCINSTR_27,
    CLBTILE6_HLCINSTR_28,
    CLBTILE6_HLCINSTR_29,
    CLBTILE6_HLCINSTR_30,
    CLBTILE6_HLCINSTR_31
};


const uint32_t CLBTILE8_HLC_initFIFOData[4] = {CLBTILE8_HLC_FIFO0_INIT, CLBTILE8_HLC_FIFO1_INIT, CLBTILE8_HLC_FIFO2_INIT, CLBTILE8_HLC_FIFO3_INIT};

uint16_t CLBTILE8HLCInstr[CLB_NUM_HLC_INSTR + 1] =
{
    CLBTILE8_HLCINSTR_0,
    CLBTILE8_HLCINSTR_1,
    CLBTILE8_HLCINSTR_2,
    CLBTILE8_HLCINSTR_3,
    CLBTILE8_HLCINSTR_4,
    CLBTILE8_HLCINSTR_5,
    CLBTILE8_HLCINSTR_6,
    CLBTILE8_HLCINSTR_7,
    CLBTILE8_HLCINSTR_8,
    CLBTILE8_HLCINSTR_9,
    CLBTILE8_HLCINSTR_10,
    CLBTILE8_HLCINSTR_11,
    CLBTILE8_HLCINSTR_12,
    CLBTILE8_HLCINSTR_13,
    CLBTILE8_HLCINSTR_14,
    CLBTILE8_HLCINSTR_15,
    CLBTILE8_HLCINSTR_16,
    CLBTILE8_HLCINSTR_17,
    CLBTILE8_HLCINSTR_18,
    CLBTILE8_HLCINSTR_19,
    CLBTILE8_HLCINSTR_20,
    CLBTILE8_HLCINSTR_21,
    CLBTILE8_HLCINSTR_22,
    CLBTILE8_HLCINSTR_23,
    CLBTILE8_HLCINSTR_24,
    CLBTILE8_HLCINSTR_25,
    CLBTILE8_HLCINSTR_26,
    CLBTILE8_HLCINSTR_27,
    CLBTILE8_HLCINSTR_28,
    CLBTILE8_HLCINSTR_29,
    CLBTILE8_HLCINSTR_30,
    CLBTILE8_HLCINSTR_31
};


const uint32_t CLBTILE7_HLC_initFIFOData[4] = {CLBTILE7_HLC_FIFO0_INIT, CLBTILE7_HLC_FIFO1_INIT, CLBTILE7_HLC_FIFO2_INIT, CLBTILE7_HLC_FIFO3_INIT};

uint16_t CLBTILE7HLCInstr[CLB_NUM_HLC_INSTR + 1] =
{
    CLBTILE7_HLCINSTR_0,
    CLBTILE7_HLCINSTR_1,
    CLBTILE7_HLCINSTR_2,
    CLBTILE7_HLCINSTR_3,
    CLBTILE7_HLCINSTR_4,
    CLBTILE7_HLCINSTR_5,
    CLBTILE7_HLCINSTR_6,
    CLBTILE7_HLCINSTR_7,
    CLBTILE7_HLCINSTR_8,
    CLBTILE7_HLCINSTR_9,
    CLBTILE7_HLCINSTR_10,
    CLBTILE7_HLCINSTR_11,
    CLBTILE7_HLCINSTR_12,
    CLBTILE7_HLCINSTR_13,
    CLBTILE7_HLCINSTR_14,
    CLBTILE7_HLCINSTR_15,
    CLBTILE7_HLCINSTR_16,
    CLBTILE7_HLCINSTR_17,
    CLBTILE7_HLCINSTR_18,
    CLBTILE7_HLCINSTR_19,
    CLBTILE7_HLCINSTR_20,
    CLBTILE7_HLCINSTR_21,
    CLBTILE7_HLCINSTR_22,
    CLBTILE7_HLCINSTR_23,
    CLBTILE7_HLCINSTR_24,
    CLBTILE7_HLCINSTR_25,
    CLBTILE7_HLCINSTR_26,
    CLBTILE7_HLCINSTR_27,
    CLBTILE7_HLCINSTR_28,
    CLBTILE7_HLCINSTR_29,
    CLBTILE7_HLCINSTR_30,
    CLBTILE7_HLCINSTR_31
};



void initCLBTILE5(uint32_t base)
{
    uint16_t i;
    //
    //  Pipeline Mode
    //
    CLB_disablePipelineMode(base);
    //
    //  Output LUT
    //
    //
    //  Equation for Output Look-Up Table Block 0 for CLBTILE5: i0&i1
    //
    CLB_configOutputLUT(base, CLB_OUT0, CLBTILE5_CFG_OUTLUT_0);

    CLB_configOutputLUT(base, CLB_OUT1, CLBTILE5_CFG_OUTLUT_1);

    //
    //  Equation for Output Look-Up Table Block 2 for CLBTILE5: i0&i1
    //
    CLB_configOutputLUT(base, CLB_OUT2, CLBTILE5_CFG_OUTLUT_2);

    CLB_configOutputLUT(base, CLB_OUT3, CLBTILE5_CFG_OUTLUT_3);

    CLB_configOutputLUT(base, CLB_OUT4, CLBTILE5_CFG_OUTLUT_4);

    CLB_configOutputLUT(base, CLB_OUT5, CLBTILE5_CFG_OUTLUT_5);
    
    CLB_configOutputLUT(base, CLB_OUT6, CLBTILE5_CFG_OUTLUT_6);

    CLB_configOutputLUT(base, CLB_OUT7, CLBTILE5_CFG_OUTLUT_7);

    //
    //  AOC
    //
    CLB_configAOC(base, CLB_AOC0, CLBTILE5_OUTPUT_COND_CTR_0);
    CLB_configAOC(base, CLB_AOC1, CLBTILE5_OUTPUT_COND_CTR_1);
    CLB_configAOC(base, CLB_AOC2, CLBTILE5_OUTPUT_COND_CTR_2);
    CLB_configAOC(base, CLB_AOC3, CLBTILE5_OUTPUT_COND_CTR_3);
    CLB_configAOC(base, CLB_AOC4, CLBTILE5_OUTPUT_COND_CTR_4);
    CLB_configAOC(base, CLB_AOC5, CLBTILE5_OUTPUT_COND_CTR_5);
    CLB_configAOC(base, CLB_AOC6, CLBTILE5_OUTPUT_COND_CTR_6);
    CLB_configAOC(base, CLB_AOC7, CLBTILE5_OUTPUT_COND_CTR_7);

    //
    // LUT 0 - 2 are configured as macros in clb_config.h; these macros are used in
    // CLB_selectLUT4Inputs and CLB_configLUT4Function
    //
    //
    //  Equation for Look-Up Table Block 0 for CLBTILE5: ~(i0&i1)

    //
    //  LUT Configuration
    //
    CLB_selectLUT4Inputs(base, CLBTILE5_CFG_LUT4_IN0, CLBTILE5_CFG_LUT4_IN1, CLBTILE5_CFG_LUT4_IN2, CLBTILE5_CFG_LUT4_IN3);
    CLB_configLUT4Function(base, CLBTILE5_CFG_LUT4_FN10, CLBTILE5_CFG_LUT4_FN2);

    //
    // FSM 0 - 2 are configured in <file>
    //

    //
    //  FSM
    //
    CLB_selectFSMInputs(base, CLBTILE5_CFG_FSM_EXT_IN0, CLBTILE5_CFG_FSM_EXT_IN1, CLBTILE5_CFG_FSM_EXTRA_IN0, CLBTILE5_CFG_FSM_EXTRA_IN1);
    CLB_configFSMNextState(base, CLBTILE5_CFG_FSM_NEXT_STATE_0, CLBTILE5_CFG_FSM_NEXT_STATE_1, CLBTILE5_CFG_FSM_NEXT_STATE_2);
    CLB_configFSMLUTFunction(base, CLBTILE5_CFG_FSM_LUT_FN10, CLBTILE5_CFG_FSM_LUT_FN2);

    //
    // Counter 0 - 2 are configured in <file>
    //

    //
    //  Counters
    //
    CLB_selectCounterInputs(base, CLBTILE5_CFG_COUNTER_RESET, CLBTILE5_CFG_COUNTER_EVENT, CLBTILE5_CFG_COUNTER_MODE_0, CLBTILE5_CFG_COUNTER_MODE_1);
    CLB_configMiscCtrlModes(base, CLBTILE5_CFG_MISC_CONTROL);
    CLB_configCounterLoadMatch(base, CLB_CTR0, CLBTILE5_COUNTER_0_LOAD_VAL, CLBTILE5_COUNTER_0_MATCH1_VAL, CLBTILE5_COUNTER_0_MATCH2_VAL);
    CLB_configCounterLoadMatch(base, CLB_CTR1, CLBTILE5_COUNTER_1_LOAD_VAL, CLBTILE5_COUNTER_1_MATCH1_VAL, CLBTILE5_COUNTER_1_MATCH2_VAL);
    CLB_configCounterLoadMatch(base, CLB_CTR2, CLBTILE5_COUNTER_2_LOAD_VAL, CLBTILE5_COUNTER_2_MATCH1_VAL, CLBTILE5_COUNTER_2_MATCH2_VAL);
    CLB_configCounterTapSelects(base, CLBTILE5_CFG_TAP_SEL);

    //
    // HLC is configured in <file>
    //

    //
    // HLC
    //
    CLB_configHLCEventSelect(base, CLBTILE5_HLC_EVENT_SEL);
    CLB_setHLCRegisters(base, CLBTILE5_HLC_R0_INIT, CLBTILE5_HLC_R1_INIT, CLBTILE5_HLC_R2_INIT, CLBTILE5_HLC_R3_INIT);

    for(i = 0; i <= CLB_NUM_HLC_INSTR; i++)
    {
        CLB_programHLCInstruction(base, i, CLBTILE5HLCInstr[i]);
    }
}

void initCLBTILE6(uint32_t base)
{
    uint16_t i;
    //
    //  Pipeline Mode
    //
    CLB_disablePipelineMode(base);
    //
    //  Output LUT
    //
    //
    //  Equation for Output Look-Up Table Block 0 for CLBTILE6: i0&i1
    //
    CLB_configOutputLUT(base, CLB_OUT0, CLBTILE6_CFG_OUTLUT_0);

    CLB_configOutputLUT(base, CLB_OUT1, CLBTILE6_CFG_OUTLUT_1);

    //
    //  Equation for Output Look-Up Table Block 2 for CLBTILE6: i0&i1
    //
    CLB_configOutputLUT(base, CLB_OUT2, CLBTILE6_CFG_OUTLUT_2);

    CLB_configOutputLUT(base, CLB_OUT3, CLBTILE6_CFG_OUTLUT_3);

    CLB_configOutputLUT(base, CLB_OUT4, CLBTILE6_CFG_OUTLUT_4);

    CLB_configOutputLUT(base, CLB_OUT5, CLBTILE6_CFG_OUTLUT_5);
    
    CLB_configOutputLUT(base, CLB_OUT6, CLBTILE6_CFG_OUTLUT_6);

    CLB_configOutputLUT(base, CLB_OUT7, CLBTILE6_CFG_OUTLUT_7);

    //
    //  AOC
    //
    CLB_configAOC(base, CLB_AOC0, CLBTILE6_OUTPUT_COND_CTR_0);
    CLB_configAOC(base, CLB_AOC1, CLBTILE6_OUTPUT_COND_CTR_1);
    CLB_configAOC(base, CLB_AOC2, CLBTILE6_OUTPUT_COND_CTR_2);
    CLB_configAOC(base, CLB_AOC3, CLBTILE6_OUTPUT_COND_CTR_3);
    CLB_configAOC(base, CLB_AOC4, CLBTILE6_OUTPUT_COND_CTR_4);
    CLB_configAOC(base, CLB_AOC5, CLBTILE6_OUTPUT_COND_CTR_5);
    CLB_configAOC(base, CLB_AOC6, CLBTILE6_OUTPUT_COND_CTR_6);
    CLB_configAOC(base, CLB_AOC7, CLBTILE6_OUTPUT_COND_CTR_7);

    //
    // LUT 0 - 2 are configured as macros in clb_config.h; these macros are used in
    // CLB_selectLUT4Inputs and CLB_configLUT4Function
    //
    //
    //  Equation for Look-Up Table Block 0 for CLBTILE6: ~(i0&i1)

    //
    //  LUT Configuration
    //
    CLB_selectLUT4Inputs(base, CLBTILE6_CFG_LUT4_IN0, CLBTILE6_CFG_LUT4_IN1, CLBTILE6_CFG_LUT4_IN2, CLBTILE6_CFG_LUT4_IN3);
    CLB_configLUT4Function(base, CLBTILE6_CFG_LUT4_FN10, CLBTILE6_CFG_LUT4_FN2);

    //
    // FSM 0 - 2 are configured in <file>
    //

    //
    //  FSM
    //
    CLB_selectFSMInputs(base, CLBTILE6_CFG_FSM_EXT_IN0, CLBTILE6_CFG_FSM_EXT_IN1, CLBTILE6_CFG_FSM_EXTRA_IN0, CLBTILE6_CFG_FSM_EXTRA_IN1);
    CLB_configFSMNextState(base, CLBTILE6_CFG_FSM_NEXT_STATE_0, CLBTILE6_CFG_FSM_NEXT_STATE_1, CLBTILE6_CFG_FSM_NEXT_STATE_2);
    CLB_configFSMLUTFunction(base, CLBTILE6_CFG_FSM_LUT_FN10, CLBTILE6_CFG_FSM_LUT_FN2);

    //
    // Counter 0 - 2 are configured in <file>
    //

    //
    //  Counters
    //
    CLB_selectCounterInputs(base, CLBTILE6_CFG_COUNTER_RESET, CLBTILE6_CFG_COUNTER_EVENT, CLBTILE6_CFG_COUNTER_MODE_0, CLBTILE6_CFG_COUNTER_MODE_1);
    CLB_configMiscCtrlModes(base, CLBTILE6_CFG_MISC_CONTROL);
    CLB_configCounterLoadMatch(base, CLB_CTR0, CLBTILE6_COUNTER_0_LOAD_VAL, CLBTILE6_COUNTER_0_MATCH1_VAL, CLBTILE6_COUNTER_0_MATCH2_VAL);
    CLB_configCounterLoadMatch(base, CLB_CTR1, CLBTILE6_COUNTER_1_LOAD_VAL, CLBTILE6_COUNTER_1_MATCH1_VAL, CLBTILE6_COUNTER_1_MATCH2_VAL);
    CLB_configCounterLoadMatch(base, CLB_CTR2, CLBTILE6_COUNTER_2_LOAD_VAL, CLBTILE6_COUNTER_2_MATCH1_VAL, CLBTILE6_COUNTER_2_MATCH2_VAL);
    CLB_configCounterTapSelects(base, CLBTILE6_CFG_TAP_SEL);

    //
    // HLC is configured in <file>
    //

    //
    // HLC
    //
    CLB_configHLCEventSelect(base, CLBTILE6_HLC_EVENT_SEL);
    CLB_setHLCRegisters(base, CLBTILE6_HLC_R0_INIT, CLBTILE6_HLC_R1_INIT, CLBTILE6_HLC_R2_INIT, CLBTILE6_HLC_R3_INIT);

    for(i = 0; i <= CLB_NUM_HLC_INSTR; i++)
    {
        CLB_programHLCInstruction(base, i, CLBTILE6HLCInstr[i]);
    }
}

void initCLBTILE8(uint32_t base)
{
    uint16_t i;
    //
    //  Pipeline Mode
    //
    CLB_disablePipelineMode(base);
    //
    //  Output LUT
    //
    //
    //  Equation for Output Look-Up Table Block 0 for CLBTILE8: i0&i1
    //
    CLB_configOutputLUT(base, CLB_OUT0, CLBTILE8_CFG_OUTLUT_0);

    CLB_configOutputLUT(base, CLB_OUT1, CLBTILE8_CFG_OUTLUT_1);

    //
    //  Equation for Output Look-Up Table Block 2 for CLBTILE8: i0&i1
    //
    CLB_configOutputLUT(base, CLB_OUT2, CLBTILE8_CFG_OUTLUT_2);

    CLB_configOutputLUT(base, CLB_OUT3, CLBTILE8_CFG_OUTLUT_3);

    CLB_configOutputLUT(base, CLB_OUT4, CLBTILE8_CFG_OUTLUT_4);

    CLB_configOutputLUT(base, CLB_OUT5, CLBTILE8_CFG_OUTLUT_5);
    
    CLB_configOutputLUT(base, CLB_OUT6, CLBTILE8_CFG_OUTLUT_6);

    CLB_configOutputLUT(base, CLB_OUT7, CLBTILE8_CFG_OUTLUT_7);

    //
    //  AOC
    //
    CLB_configAOC(base, CLB_AOC0, CLBTILE8_OUTPUT_COND_CTR_0);
    CLB_configAOC(base, CLB_AOC1, CLBTILE8_OUTPUT_COND_CTR_1);
    CLB_configAOC(base, CLB_AOC2, CLBTILE8_OUTPUT_COND_CTR_2);
    CLB_configAOC(base, CLB_AOC3, CLBTILE8_OUTPUT_COND_CTR_3);
    CLB_configAOC(base, CLB_AOC4, CLBTILE8_OUTPUT_COND_CTR_4);
    CLB_configAOC(base, CLB_AOC5, CLBTILE8_OUTPUT_COND_CTR_5);
    CLB_configAOC(base, CLB_AOC6, CLBTILE8_OUTPUT_COND_CTR_6);
    CLB_configAOC(base, CLB_AOC7, CLBTILE8_OUTPUT_COND_CTR_7);

    //
    // LUT 0 - 2 are configured as macros in clb_config.h; these macros are used in
    // CLB_selectLUT4Inputs and CLB_configLUT4Function
    //
    //
    //  Equation for Look-Up Table Block 0 for CLBTILE8: ~(i0&i1)

    //
    //  LUT Configuration
    //
    CLB_selectLUT4Inputs(base, CLBTILE8_CFG_LUT4_IN0, CLBTILE8_CFG_LUT4_IN1, CLBTILE8_CFG_LUT4_IN2, CLBTILE8_CFG_LUT4_IN3);
    CLB_configLUT4Function(base, CLBTILE8_CFG_LUT4_FN10, CLBTILE8_CFG_LUT4_FN2);

    //
    // FSM 0 - 2 are configured in <file>
    //

    //
    //  FSM
    //
    CLB_selectFSMInputs(base, CLBTILE8_CFG_FSM_EXT_IN0, CLBTILE8_CFG_FSM_EXT_IN1, CLBTILE8_CFG_FSM_EXTRA_IN0, CLBTILE8_CFG_FSM_EXTRA_IN1);
    CLB_configFSMNextState(base, CLBTILE8_CFG_FSM_NEXT_STATE_0, CLBTILE8_CFG_FSM_NEXT_STATE_1, CLBTILE8_CFG_FSM_NEXT_STATE_2);
    CLB_configFSMLUTFunction(base, CLBTILE8_CFG_FSM_LUT_FN10, CLBTILE8_CFG_FSM_LUT_FN2);

    //
    // Counter 0 - 2 are configured in <file>
    //

    //
    //  Counters
    //
    CLB_selectCounterInputs(base, CLBTILE8_CFG_COUNTER_RESET, CLBTILE8_CFG_COUNTER_EVENT, CLBTILE8_CFG_COUNTER_MODE_0, CLBTILE8_CFG_COUNTER_MODE_1);
    CLB_configMiscCtrlModes(base, CLBTILE8_CFG_MISC_CONTROL);
    CLB_configCounterLoadMatch(base, CLB_CTR0, CLBTILE8_COUNTER_0_LOAD_VAL, CLBTILE8_COUNTER_0_MATCH1_VAL, CLBTILE8_COUNTER_0_MATCH2_VAL);
    CLB_configCounterLoadMatch(base, CLB_CTR1, CLBTILE8_COUNTER_1_LOAD_VAL, CLBTILE8_COUNTER_1_MATCH1_VAL, CLBTILE8_COUNTER_1_MATCH2_VAL);
    CLB_configCounterLoadMatch(base, CLB_CTR2, CLBTILE8_COUNTER_2_LOAD_VAL, CLBTILE8_COUNTER_2_MATCH1_VAL, CLBTILE8_COUNTER_2_MATCH2_VAL);
    CLB_configCounterTapSelects(base, CLBTILE8_CFG_TAP_SEL);

    //
    // HLC is configured in <file>
    //

    //
    // HLC
    //
    CLB_configHLCEventSelect(base, CLBTILE8_HLC_EVENT_SEL);
    CLB_setHLCRegisters(base, CLBTILE8_HLC_R0_INIT, CLBTILE8_HLC_R1_INIT, CLBTILE8_HLC_R2_INIT, CLBTILE8_HLC_R3_INIT);

    for(i = 0; i <= CLB_NUM_HLC_INSTR; i++)
    {
        CLB_programHLCInstruction(base, i, CLBTILE8HLCInstr[i]);
    }
}

void initCLBTILE7(uint32_t base)
{
    uint16_t i;
    //
    //  Pipeline Mode
    //
    CLB_disablePipelineMode(base);
    //
    //  Output LUT
    //
    //
    //  Equation for Output Look-Up Table Block 0 for CLBTILE7: i0&i1
    //
    CLB_configOutputLUT(base, CLB_OUT0, CLBTILE7_CFG_OUTLUT_0);

    CLB_configOutputLUT(base, CLB_OUT1, CLBTILE7_CFG_OUTLUT_1);

    //
    //  Equation for Output Look-Up Table Block 2 for CLBTILE7: i0&i1
    //
    CLB_configOutputLUT(base, CLB_OUT2, CLBTILE7_CFG_OUTLUT_2);

    CLB_configOutputLUT(base, CLB_OUT3, CLBTILE7_CFG_OUTLUT_3);

    CLB_configOutputLUT(base, CLB_OUT4, CLBTILE7_CFG_OUTLUT_4);

    CLB_configOutputLUT(base, CLB_OUT5, CLBTILE7_CFG_OUTLUT_5);
    
    CLB_configOutputLUT(base, CLB_OUT6, CLBTILE7_CFG_OUTLUT_6);

    CLB_configOutputLUT(base, CLB_OUT7, CLBTILE7_CFG_OUTLUT_7);

    //
    //  AOC
    //
    CLB_configAOC(base, CLB_AOC0, CLBTILE7_OUTPUT_COND_CTR_0);
    CLB_configAOC(base, CLB_AOC1, CLBTILE7_OUTPUT_COND_CTR_1);
    CLB_configAOC(base, CLB_AOC2, CLBTILE7_OUTPUT_COND_CTR_2);
    CLB_configAOC(base, CLB_AOC3, CLBTILE7_OUTPUT_COND_CTR_3);
    CLB_configAOC(base, CLB_AOC4, CLBTILE7_OUTPUT_COND_CTR_4);
    CLB_configAOC(base, CLB_AOC5, CLBTILE7_OUTPUT_COND_CTR_5);
    CLB_configAOC(base, CLB_AOC6, CLBTILE7_OUTPUT_COND_CTR_6);
    CLB_configAOC(base, CLB_AOC7, CLBTILE7_OUTPUT_COND_CTR_7);

    //
    // LUT 0 - 2 are configured as macros in clb_config.h; these macros are used in
    // CLB_selectLUT4Inputs and CLB_configLUT4Function
    //
    //
    //  Equation for Look-Up Table Block 0 for CLBTILE7: ~(i0&i1)

    //
    //  LUT Configuration
    //
    CLB_selectLUT4Inputs(base, CLBTILE7_CFG_LUT4_IN0, CLBTILE7_CFG_LUT4_IN1, CLBTILE7_CFG_LUT4_IN2, CLBTILE7_CFG_LUT4_IN3);
    CLB_configLUT4Function(base, CLBTILE7_CFG_LUT4_FN10, CLBTILE7_CFG_LUT4_FN2);

    //
    // FSM 0 - 2 are configured in <file>
    //

    //
    //  FSM
    //
    CLB_selectFSMInputs(base, CLBTILE7_CFG_FSM_EXT_IN0, CLBTILE7_CFG_FSM_EXT_IN1, CLBTILE7_CFG_FSM_EXTRA_IN0, CLBTILE7_CFG_FSM_EXTRA_IN1);
    CLB_configFSMNextState(base, CLBTILE7_CFG_FSM_NEXT_STATE_0, CLBTILE7_CFG_FSM_NEXT_STATE_1, CLBTILE7_CFG_FSM_NEXT_STATE_2);
    CLB_configFSMLUTFunction(base, CLBTILE7_CFG_FSM_LUT_FN10, CLBTILE7_CFG_FSM_LUT_FN2);

    //
    // Counter 0 - 2 are configured in <file>
    //

    //
    //  Counters
    //
    CLB_selectCounterInputs(base, CLBTILE7_CFG_COUNTER_RESET, CLBTILE7_CFG_COUNTER_EVENT, CLBTILE7_CFG_COUNTER_MODE_0, CLBTILE7_CFG_COUNTER_MODE_1);
    CLB_configMiscCtrlModes(base, CLBTILE7_CFG_MISC_CONTROL);
    CLB_configCounterLoadMatch(base, CLB_CTR0, CLBTILE7_COUNTER_0_LOAD_VAL, CLBTILE7_COUNTER_0_MATCH1_VAL, CLBTILE7_COUNTER_0_MATCH2_VAL);
    CLB_configCounterLoadMatch(base, CLB_CTR1, CLBTILE7_COUNTER_1_LOAD_VAL, CLBTILE7_COUNTER_1_MATCH1_VAL, CLBTILE7_COUNTER_1_MATCH2_VAL);
    CLB_configCounterLoadMatch(base, CLB_CTR2, CLBTILE7_COUNTER_2_LOAD_VAL, CLBTILE7_COUNTER_2_MATCH1_VAL, CLBTILE7_COUNTER_2_MATCH2_VAL);
    CLB_configCounterTapSelects(base, CLBTILE7_CFG_TAP_SEL);

    //
    // HLC is configured in <file>
    //

    //
    // HLC
    //
    CLB_configHLCEventSelect(base, CLBTILE7_HLC_EVENT_SEL);
    CLB_setHLCRegisters(base, CLBTILE7_HLC_R0_INIT, CLBTILE7_HLC_R1_INIT, CLBTILE7_HLC_R2_INIT, CLBTILE7_HLC_R3_INIT);

    for(i = 0; i <= CLB_NUM_HLC_INSTR; i++)
    {
        CLB_programHLCInstruction(base, i, CLBTILE7HLCInstr[i]);
    }
}
